### ISSUE TITLE
Question about figure 1 in paper

### ISSUE THREAD

**Issue by sihouzi21c** [ziplab/PTQD#7]
Figure 1 in your paper is experimented on CelebA-HQ 256x256, however there is no illustration of this part in paper.
Could you tell me in this experiment: (1) #steps of LDM; (2)FID performance of PTQD and Q-diffusion?
Thanks a lot.

**Comment by ThisisBillhe** [comment]
We use 200 DDIM steps, as LDM's official repo did. However, I cannot reproduce their reported results. You may refer to [here](https://github.com/CompVis/latent-diffusion/issues/213).
