### ISSUE TITLE
Correlated relationship asking

### ISSUE THREAD

**Issue by digbangbang** [ziplab/PTQD#8]
Hi,
I have a question for the correlation relationship in the 4.1 in the paper.
After getting this below,
![image](https://github.com/ziplab/PTQD/assets/78746384/c268565f-01f4-4987-837c-2658e21d8f74)
How to get this below?
![image](https://github.com/ziplab/PTQD/assets/78746384/806c70be-e929-4cc8-abbe-7137fe46a5c4)

**Comment by ThisisBillhe** [comment]
Based on Eq. (6) in the paper, we observe that a part of the quantization noise is linearly related to the full-precision model's output. Therefore, we disentangle the quantization noise into the correlated part and the uncorrelated part (see Eq. (7)).

**Comment by digbangbang** [comment]
Thanks for answering!
But the Y in Eq.(6) maybe is the input of the normalization layer(paper mention it in the proposition 1), it is not equal to the output of the full-precision noise prediction network. So, I think the 
![image](https://github.com/ziplab/PTQD/assets/78746384/b7308835-1042-4b58-974b-9ebeece650fb) equals to the 
![image](https://github.com/ziplab/PTQD/assets/78746384/91c173cd-ae33-4be4-930a-b22fc3b29622), but the 
![image](https://github.com/ziplab/PTQD/assets/78746384/50581faa-c29a-4e72-9d0f-e1b2254e328d) doesn't equal to the 
![image](https://github.com/ziplab/PTQD/assets/78746384/5801bb6a-5c12-4eb4-999d-346a56a01d2e). 

Maybe you got the relationship from the experiments? If there is something wrong I understood, pls let me know. Thanks!

**Comment by ThisisBillhe** [comment]
The full-precision output of normalization is 
![image](https://github.com/ziplab/PTQD/assets/56794062/a5a1b310-cb1b-48fb-b3c5-ad000c084a52)
where the mean and variance are scalars. So it is also linearly related to Y.

**Comment by digbangbang** [comment]
oh yes, I got it! Thanks!
