### ISSUE TITLE
num_samples=0

### ISSUE THREAD

**Issue by digbangbang** [ziplab/PTQD#9]
Hi, I met the problem when `python3 quant_scripts/quantize_ldm_brecq.py`
It came out ValueError: num_samples should be a positive integer value, but got num_samples=0

I noted that the collect_diffusion_input_imagenet.py use the DDIMsampler, but the DDPM.py maybe is not used in this project,
so it came the question, and uncomment line 987-988 in ldm/models/diffusion/ddpm.py seems didn't work.

So what can I do for this problem?

**Comment by MingGuo-alt** [comment]
Hello, have you solved this problem? I have the same problem, please let me know if you solve it! 
Thanks!

**Comment by Ali-Flt** [comment]
I think you should see the comment at the beginning of the `collect_diffusion_input_imagenet.py` file

**Comment by aaaloser** [comment]
> I think you should see the comment at the beginning of the `collect_diffusion_input_imagenet.py` file

Thanks for your anwser, and it's really a stupid mistake.😂
